<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Version>1.0.0</Version>
        <Description>The Silliest Among Us Mod</Description>
        <Authors>WanderingPixel</Authors>
    </PropertyGroup>

    <Import Project="AmongUs.props"/>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.png"/>
        <EmbeddedResource Include="Resources\**\*.wav"/>
        <EmbeddedResource Include="Resources\**\*.bundle"/>
	    <EmbeddedResource Include="modinfo.json"/>
    </ItemGroup>
</Project>
