name: Compilation Workflow

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - name: Delete Old artifacts
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log-level: 'error'
          min-bytes: '0'

      - name: Upload RFS.dll artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReachForStars.dll
          path: src/bin/Release/net6.0/ReachForStars.dll
          
      - name: Draft A Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: src/bin/Release/net6.0/ReachForStars.dll
          
